### ISSUE TITLE
Alternative hypotesis

### ISSUE THREAD

**Issue by LocoMatt** [edoannunziata/dieboldmariano#1]
How should "one sided" and "two sided" alternatives be interpreted. 
"two sided" - both forecasts have diffrent levels of accuracy?
"one sided" - F1 is more accurate than F2 - that's what I understand from source code.

**Comment by edoannunziata** [comment]
Hi, thanks for writing and my apologies if that point was not clear.

The choice of a one-sided or a two-sided test does not affect the computation of the test statistic, but it does change the resulting p-value.

A two-sided test has the following hypotheses:
Null: F1 and F2 have the same level of accuracy.
Alternative: F1 and F2 have different levels of accuracy.

A one-sided test would be, instead:
Null: F2 has at least the same accuracy as F1.
Alternative: F1 is more accurate than F2.

In both cases, the p-value has the usual interpretation, namely the probability of observing an effect at least as large as the one the data shows, assuming the null hypothesis is true.

The choice between the two kinds of tests is offered as a convenience to the user, even though the internal behavior is mostly unchanged.

**Comment by LocoMatt** [comment]
Thank you for clarifying and quick response!
